Just added a few things
Cosmic-Search/Universe pull request #1
Opened 2017-02-24 23:56 UTC by card100

2017-02-25 12:27 UTC, CosmicWebServices requested changes

2017-02-25 12:27 UTC, CosmicWebServices commented on client/home.html
> +	<style>
Not that sure I am liking this style addition. Usually you do not want style unless you really have to when using a library especially when it has a standard for design

2017-02-25 12:27 UTC, CosmicWebServices commented on client/home.html
> +			<a class="brand-logo center" href="/">Cosmic Search Universe</a> <a class="link" href="/news">News</a>
I think the news search link could have a better place but not here.

2017-02-25 12:27 UTC, CosmicWebServices commented
Sorry if I am being too picky I just have a certain design philosophy when it comes to sites.

2017-02-25 21:02 UTC, card100 commented
I made the <style> because I can't find your css file

2017-02-25 21:05 UTC, CosmicWebServices commented
@card100 I have no problem with that I just do not like the styles in it. Also, I am using the materializecss.com library since I am trying to use the material design guidelines to make this.

But theme support are coming soon so you can start making one now if you want.

2017-02-27 18:45 UTC, card100 commented
Should I then delete this branch?

2017-02-27 18:45 UTC, closed without merging

2017-02-27 19:52 UTC, CosmicWebServices commented
Sure